version: '3.8'

services:

  db:
    image: postgres:17-alpine
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: text_analyzer
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend-service:
    build: ./frontend
    ports:
      - "8888:80"
  
  backend-service:
    build: ./backend
    ports:
      - "5001:5000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: mysecretpassword
      DB_NAME: text_analyzer
    depends_on:
      - db

volumes:
  postgres_data: